Repository Scribbie-Notes/notes-app, pull requests merged in 2024-11, with the labels that each got.

#365 Refactor: Remove all duplicate note routes
  backend/Routes/Router.js
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#355 Feature: Add Edit option for archive notes
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: good first issue, gssoc-ext, level2

#363 Modified all event routes and added default color
  backend/Routes/eventRoutes.js
  frontend/src/components/Calendar/Calendar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#364 Add tailwind class to wrap event title
  frontend/src/components/Calendar/Calendar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#366 Make Navbar Responsive
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Home/Home.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#367 Added update Pin method for archive notes
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3

#374 Added view modal for archive notes (works for pinned note as well)
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#375 Save theme in local storage and fetch it after refresh
  frontend/src/components/Navbar.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3

#376 Fixed home page card disable bug & removed hardcoding URLs
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#380 Added custom hook for Add, Edit notes
  backend/controllers/noteControllers.js
  frontend/src/hooks/noteActions.jsx
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#381 Added event description field in frontend & backend query to save the same
  backend/Routes/eventRoutes.js
  backend/models/eventModel.js
  frontend/src/components/Calendar/Calendar.jsx
  frontend/src/components/Modal.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#386 Added sync with google calendar to fetch events and show the same
  frontend/.env.example
  frontend/package.json
  frontend/src/components/Calendar/Calendar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#387 Added export button to download note in txt
  frontend/src/components/Cards/NoteCard.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#388 Added pre-defined templates for Notes
  frontend/src/pages/Home/AddEditNotes.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Home/Templates.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#390 "Progress bar added & scroll to top button modified"
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Hero/Hero.jsx
  frontend/src/components/Progressbar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#391 Added mardown and code block support + Adjusted width of new note
  backend/Makefile
  backend/controllers/noteControllers.js
  frontend/src/pages/Home/AddEditNotes.jsx
  frontend/src/pages/Home/Home.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#396 Added the security policy
  SECURITY.md
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#404 Sort Notes by date in Ascending/Descending order
  frontend/src/pages/Home/Home.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#405 Added revert button to get back last changes in edit Note
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#406 Added contributors page and link in footer
  frontend/src/App.jsx
  frontend/src/components/Contributors/Contributors.css
  frontend/src/components/Contributors/Contributors.jsx
  frontend/src/components/Footer.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#407 Added search by tag and search by title for Notes
  frontend/src/components/Navbar.jsx
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/pages/Home/Home.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#423 Added share button to view note by link
  backend/Routes/noteRoutes.js
  backend/controllers/noteControllers.js
  backend/package.json
  frontend/src/components/Cards/NoteCard.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#424 Fix sign up
  backend/Routes/user.routes.js
  backend/controllers/user.controllers.js
  backend/models/userModel.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#415 added loader to calender page
  frontend/src/components/Calendar/Calendar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1
