Repository Scribbie-Notes/notes-app, pull requests merged in 2024-10, with the labels that each got.

#19 Add Form Field Validations for Email, Password, and Name during SignUp
  backend/index.js
  frontend/src/pages/Signup/Signup.jsx
  frontend/src/utils/helper.js
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#56 Feature/gitignore
  .gitignore
  backend/.gitignore
  frontend/.gitignore
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#110 Additon of All Contributors | Issue #109
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#120 Fix: Exclude node_modules in .gitignore
  .gitignore
Labels: bug, good first issue, gssoc-ext, hacktoberfest-accepted, level 1

#121 Feat: Password hashed
  backend/index.js
Labels: bug, gssoc-ext, hacktoberfest-accepted, level 2

#123 added modal for logout confirmation
  frontend/src/components/Cards/ProfileInfo.jsx
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, level 1

#111 Enhanced Footer and made it responsive #96
  .gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/src/components/Footer.jsx
  frontend/src/components/Footer/logo.png
  frontend/src/components/Hero/Hero.jsx
  frontend/src/components/Scroll-on-top/ScrollOnTop.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#133 Express.Router() has been added to simplify index.js file
  backend/Routes/Router.js
  backend/index.js
  backend/utilities.js
Labels: bug, gssoc-ext, hacktoberfest-accepted, level 2

#131 modified the testominal page with slick animations
  frontend/src/components/Testimonial.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3

#142 added gsap to animate the website
  frontend/src/App.jsx
  frontend/src/components/Hero/Hero.jsx
  frontend/src/components/Navbar.jsx
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 3

#144 scroll bar added : Added scroll bar on your website #140 done
  frontend/src/index.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2

#150 fix: all api's getting fail with 403 error after login/signup
  backend/Routes/Router.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#155 added navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Tabs.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#156 Updated-footer-ui
  frontend/src/components/Footer.jsx
  frontend/src/components/Hero/Hero.jsx
  frontend/src/components/Pricing.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#158 feat : adding background color on notes
  backend/Routes/Router.js
  backend/models/noteModel.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Cards/NoteCard.jsx
  frontend/src/pages/Home/AddEditNotes.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#159 Fix 404 Not Found Issue After Deployment
  backend/vercel.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#166 [Feat]: FAQ page added successfully
  frontend/src/assets/images/cross.svg
  frontend/src/components/Faq.jsx
  frontend/src/components/Hero/Hero.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#168 adding background color functionality of multiple notes together
  backend/Routes/Router.js
  frontend/src/components/Cards/NoteCard.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#165 Implement basic text formatting options in note editor
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Cards/NoteCard.jsx
  frontend/src/pages/Home/AddEditNotes.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#178 Add Bulk Delete Functionality for Notes
  backend/Routes/Router.js
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#175 Fix Header Not Displaying on Various Routes
  frontend/src/App.jsx
  frontend/src/components/Contact/Contact.jsx
  frontend/src/components/Pricing.jsx
  frontend/src/components/Testimonial.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#180 [feat]Add Undo Functionality for Deleted Notes
  backend/Routes/Router.js
  backend/models/noteModel.js
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#182 Added Contributor's Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Contributors/Contributors.css
  frontend/src/components/Contributors/Contributors.jsx
  frontend/src/components/Footer.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#187 Implement Pinning and Unpinning Multiple Notes
  backend/Routes/Router.js
  frontend/src/components/Cards/NoteCard.jsx
  frontend/src/pages/Home/Home.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#196 Add Feature to Archive Notes
  backend/Routes/Router.js
  backend/models/noteModel.js
  frontend/src/App.jsx
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
  frontend/src/components/Cards/ProfileInfo.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#195 Implemented Dynamic Search Result Display for the homepage Search bar
  backend/Routes/Router.js
  backend/index.js
  backend/models/noteModel.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Cards/NoteCard.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/SearchBar/SearchBar.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#199 added contact us page
  frontend/src/components/Contact/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#207 Made animations visible every time it get's into the view, and removed repetition of navbar component among the home page.
  frontend/src/components/Hero/Hero.jsx
  frontend/src/components/Pricing.jsx
  frontend/src/components/Testimonial.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#209 preloader added
  .gitignore
  frontend/.env.development
  frontend/src/App.jsx
  frontend/src/components/Preloader.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#211 #198 Signup added on Navbar
  frontend/src/components/Navbar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#228 Make Active Route Link Color Distinct for Improved Navigation
  frontend/src/components/Tabs.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#230 improved the Ui of the About Us page
  frontend/src/components/About/About.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#231 Fixed the bug
  frontend/src/components/About/About.jsx
  frontend/src/components/Contact/Contact.jsx
  frontend/src/components/Footer.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#174 add dark mode
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Tabs.jsx
  frontend/src/components/Toggle.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#251 Fix Feedback Button to Display Modal in Footer
  frontend/src/components/Footer.jsx
Labels: bug, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#238 Fix mongodb query to update note
  backend/Routes/Router.js
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#255 Fix: Hide Login and Signup Buttons When User is Logged In
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/setupProxy.js
  frontend/src/utils/axiosInstance.js
  frontend/src/utils/constants.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#240 Made height of add note smaller to fit screen
  frontend/src/components/Input/AddAttachmentInput.jsx
  frontend/src/components/Input/TagInput.jsx
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#241 Added un-archive feature
  backend/Routes/Router.js
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
  frontend/src/pages/Home/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#262 Feat: Adding ContactUs Backend Functionality
  backend/Routes/Router.js
  backend/mail/contactUsMailSender.js
  frontend/src/components/Contact/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#253 Updated README with additional details and badges
  README.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#268 Create LICENSE
  LICENSE
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#267 Add background color feature for multiple archived notes
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#200 Integrated TinyMCE to notes app
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#271 Done the enhancements and also added some new sections
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#210 profile photo update issue
  backend/.env.example
  backend/Routes/Router.js
  backend/Routes/uploads/profilePhoto-1729164520517-905517046.jpg
  backend/Routes/uploads/profilePhoto-1729164538736-40559474.jpg
  backend/Routes/uploads/profilePhoto-1729164567074-811265604.jpg
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/ProfilePage/ProfilePage.jsx
  frontend/src/pages/Signup/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#281 updated the code base
  backend/Routes/Router.js
  backend/models/userModel.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#288 Fix the error showing on signup and login
  backend/Routes/Router.js
  backend/models/userModel.js
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/Signup/Signup.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3

#277 Add mic succefully
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#293 Remove hard-coding of URLs and use env variables
  frontend/src/components/About/About.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/ProfilePage/ProfilePage.jsx
  frontend/src/setupProxy.js
  frontend/src/utils/axiosInstance.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#292 Added scrollbar and fixed margins for responsiveness for Add Note
  backend/Routes/Router.js
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#296 Implemented logout modal functionality
  backend/Routes/Router.js
  backend/index.js
  frontend/src/components/About/About.jsx
  frontend/src/components/Cards/ProfileInfo.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/Signup/Signup.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#304 Navbar responsive
  frontend/src/components/Contact/Contact.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Tabs.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#294 rate limiter to login api
  backend/Routes/Router.js
  backend/package-lock.json
  backend/package.json
Labels: gssoc-ext, hacktoberfest-accepted, level3

#316 Apply validations in all forms
  frontend/src/utils/helper.js
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#318 Add GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/detect-duplicate-issues.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#320 Fix mongo env variable usage and backend server crash
  backend/index.js
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#321 Added app version page
  frontend/src/components/Footer.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#326 Added new contact collection for saving Contact Us info
  backend/Routes/Router.js
  backend/models/contactModel.js
  frontend/src/components/Contact/Contact.jsx
  frontend/src/components/Navbar.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#299 Readability: Refactor Backend File Structure
  backend/.env.example
  backend/Routes/note.routes.js
  backend/Routes/user.routes.js
  backend/controllers/note.controllers.js
  backend/controllers/user.controllers.js
  backend/index.js
  backend/mail/contactUsMailSender.js
  backend/mail/sendMail.js
  backend/middlewares/user.middlewares.js
  backend/models/feedbackModel.js
  backend/models/noteModel.js
  backend/models/userModel.js
  backend/package.json
  backend/utils/const.js
  backend/utils/multer.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#331 Fix Logout Functionality Across Pages
  frontend/src/App.jsx
  frontend/src/components/Cards/ProfileInfo.jsx
  frontend/src/components/Pricing.jsx
  frontend/src/components/Testimonial.jsx
  frontend/src/pages/ProfilePage/ProfilePage.jsx
  frontend/tailwind.config.js
  package-lock.json
  package.json
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3

#330 Implement Auto-Labeling Workflow for GitHub
  .github/auto-label.yml
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#340 Fix: Unarchive Notes Functionality and Endpoint Response
  backend/Routes/noteRoutes.js
  backend/controllers/noteControllers.js
  backend/index.js
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#341 fix : Add/Update Background Color for Archived Notes
  backend/Routes/noteRoutes.js
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#343 Feature: Add Bulk Pin/Unpin Functionality for Archived Notes
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#347 [feat] Add Calendar Functionality with Event Addition Capability
  backend/Routes/eventRoutes.js
  backend/index.js
  backend/models/eventModel.js
  frontend/src/App.jsx
  frontend/src/components/Calendar/Calendar.jsx
  frontend/src/components/Tabs.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#348 Add Undo Functionality for Deletion of Archived Notes
  backend/Routes/noteRoutes.js
  backend/controllers/noteControllers.js
  backend/middlewares/user.middlewares.js
  frontend/src/components/ArchivedNotes/ArchivedNotes.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#353 Fixed update note in frontend and backend
  backend/Routes/Router.js
  backend/Routes/noteRoutes.js
  backend/controllers/noteControllers.js
  frontend/src/pages/Home/AddEditNotes.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level3

#359 Add Functionality to Delete Past or Unimportant Events
  frontend/src/components/Calendar/Calendar.jsx
  frontend/src/components/Modal.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2
